version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes","--save","60","1"]
    ports: ["127.0.0.1:6379:6379"]
    volumes: [rag_redis_data:/data]

  redisinsight:
    image: redis/redisinsight:latest
    ports: ["127.0.0.1:5540:5540"]  # <-- use 5540 (not 8001)
    depends_on: [redis]
volumes:
  rag_redis_data:
